In [53]:
import pandas as pd
import numpy as np

In [54]:
df2021 = pd.read_csv('tn_2021_results.csv')
df2026 = pd.read_csv('tn_2026_results.csv')
master= pd.read_csv('constituency_master.csv')

In [55]:
df2021.head(5)

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro
1,Gummidipundi,1,PRAKASH M,PMK,75514,78.08,GEN,Chennai Metro
2,Gummidipundi,1,USHA,NTK,11701,78.08,GEN,Chennai Metro
3,Gummidipundi,1,DILLIY K.M,DMDK,2576,78.08,GEN,Chennai Metro
4,Gummidipundi,1,None Of The Above,NOTA,1783,78.08,GEN,Chennai Metro

In [56]:
df2026.head(5)

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro
1,Gummidipoondi,1,SUDHAKAR.V,AIADMK,66375,NaN,GEN,Chennai Metro
2,Gummidipoondi,1,T.J.GOVINDARAJAN,DMK,62492,NaN,GEN,Chennai Metro
3,Gummidipoondi,1,"R.SRIDAR. B.L.,",NTK,4756,NaN,GEN,Chennai Metro
4,Gummidipoondi,1,NOTA,NOTA,937,NaN,GEN,Chennai Metro

In [57]:
master.head()

   ac_number  constituency    district         region reserved
0          1  Gummidipundi  Tiruvallur  Chennai Metro      GEN
1          2       Ponneri  Tiruvallur  Chennai Metro       SC
2          3     Tiruttani  Tiruvallur  Chennai Metro      GEN
3          4   Thiruvallur  Tiruvallur  Chennai Metro      GEN
4          5   Poonamallee  Tiruvallur  Chennai Metro       SC

In [58]:
df2021.shape

(4232, 8)

In [59]:
df2026.shape

(4257, 8)

In [60]:
master.shape

(234, 5)

In [61]:
master.info()

<class 'pandas.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ac_number     234 non-null    int64
 1   constituency  234 non-null    str
 2   district      234 non-null    str
 3   region        234 non-null    str
 4   reserved      234 non-null    str
dtypes: int64(1), str(4)
memory usage: 9.3 KB

In [62]:
df2026.isnull().sum()

constituency       0
ac_number          0
candidate          0
party              0
votes              0
turnout         4257
reserved           0
region             0
dtype: int64

In [63]:
df2021['party'].unique()

<StringArray>
[                                          'DMK',
                                           'PMK',
                                           'NTK',
                                          'DMDK',
                                          'NOTA',
                                           'BSP',
                                           'IJK',
                                           'IND',
                'Anaithu Makkal Arasiyal Katchi',
                                           'INC',
 ...
                      'Ambedkar Political Party',
        'All India MGR Makkal Munnetra Kazhagam',
                             'Naam Indiar Party',
                 'Desa Makkal Munnetrak Kazhgam',
                      'South India Forward Bloc',
 'Aanaithinthiya Jananayaka Pathukappu Kazhagam',
                'Universal Brotherhood Movement',
     'Anaithu Ulaga Tamilargal Munnetra Kalagam',
                           'Ulaga Makkal Katchi',
        'Tamilnadu Mahatma Gandhi Makkal Katchi']
Length: 109, dtype: str

In [64]:
df2026['party'].unique()

<StringArray>
[                                                 'TVK',
                                               'AIADMK',
                                                  'DMK',
                                                  'NTK',
                                                 'NOTA',
                                  'Bahujan Samaj Party',
        'Aanaithinthiya Jananayaka Pathukappu Kazhagam',
                                                  'IND',
 'Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi',
                                                  'INC',
 ...
                 'Ezhuchi Tamilargal Munnetra Kazhagam',
           'Ahila India Dhayaga Makkal Munnetra Katchi',
 'Communist Party of India (Marxist-Leninist) Red Star',
                    'Puthiya Makkal Tamil Desam Katchi',
          'Nam Naadu Nam Makkal Nam Ethirkaalam Katchi',
                       'Desa Makkal Munnetrak Kazhagam',
                               'Bharatha Makkal Katchi',
                           'Kamarajar Deseeya Congress',
                                 'Rashtriya Janata Dal',
                               'Indian Christian Front']
Length: 105, dtype: str

In [65]:
df2021['party'].value_counts()

party
IND                                          2073
NTK                                           234
NOTA                                          234
AIADMK                                        191
DMK                                           188
                                             ...
South India Forward Bloc                        1
Universal Brotherhood Movement                  1
Anaithu Ulaga Tamilargal Munnetra Kalagam       1
Ulaga Makkal Katchi                             1
Tamilnadu Mahatma Gandhi Makkal Katchi          1
Name: count, Length: 109, dtype: int64

In [66]:
df2026['party'].value_counts()

party
IND                                           2209
NTK                                            234
NOTA                                           234
TVK                                            233
DMK                                            176
                                              ...
Ahila India Dhayaga Makkal Munnetra Katchi       1
Bharatha Makkal Katchi                           1
Kamarajar Deseeya Congress                       1
Rashtriya Janata Dal                             1
Indian Christian Front                           1
Name: count, Length: 105, dtype: int64

In [67]:
df2021_sorted = df2021.sort_values(
    ['ac_number', 'votes'],
    ascending=[True, False]
)

In [68]:
df2021_sorted.head(20)

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro
1,Gummidipundi,1,PRAKASH M,PMK,75514,78.08,GEN,Chennai Metro
2,Gummidipundi,1,USHA,NTK,11701,78.08,GEN,Chennai Metro
3,Gummidipundi,1,DILLIY K.M,DMDK,2576,78.08,GEN,Chennai Metro
4,Gummidipundi,1,None Of The Above,NOTA,1783,78.08,GEN,Chennai Metro
5,Gummidipundi,1,NAGARAJ S,BSP,1038,78.08,GEN,Chennai Metro
6,Gummidipundi,1,SARAVANAN V,IJK,816,78.08,GEN,Chennai Metro
7,Gummidipundi,1,SARAVANAN E,IND,532,78.08,GEN,Chennai Metro
8,Gummidipundi,1,DEVANATHAN R,IND,482,78.08,GEN,Chennai Metro
9,Gummidipundi,1,LAKSHMI R,IND,374,78.08,GEN,Chennai Metro
10,Gummidipundi,1,PRAKASH K,IND,351,78.08,GEN,Chennai Metro
11,Gummidipundi,1,GOWTHAM J,Anaithu Makkal Arasiyal Katchi,254,78.08,GEN,Chennai Metro
12,Gummidipundi,1,PRAKASH M,IND,196,78.08,GEN,Chennai Metro
13,Ponneri,2,DURAI. CHANDRASEKAR,INC,94528,78.20,SC,Chennai Metro
14,Ponneri,2,BALARAMAN. P,AIADMK,84839,78.20,SC,Chennai Metro
15,Ponneri,2,MAHESWARI. A,NTK,19027,78.20,SC,Chennai Metro
16,Ponneri,2,DESINGURAJAN. D,MNM,5394,78.20,SC,Chennai Metro
17,Ponneri,2,PON. RAJA,AMMK,2832,78.20,SC,Chennai Metro
18,Ponneri,2,None Of The Above,NOTA,1554,78.20,SC,Chennai Metro
19,Ponneri,2,BHAVANI ILAVENIL. J,BSP,1106,78.20,SC,Chennai Metro

In [69]:
winners2021 = df2021_sorted.groupby('ac_number').first().reset_index()

In [70]:
winners2021.head()

,ac_number,constituency,candidate,party,votes,turnout,reserved,region
0,1,Gummidipundi,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro
1,2,Ponneri,DURAI. CHANDRASEKAR,INC,94528,78.20,SC,Chennai Metro
2,3,Tiruttani,S.Chandran,DMK,120314,78.76,GEN,Chennai Metro
3,4,Thiruvallur,"RAAJENDRAN, V.G.",DMK,107709,77.20,GEN,Chennai Metro
4,5,Poonamallee,Krishnaswamy A,DMK,149578,72.99,SC,Chennai Metro

In [71]:
winners2021.shape

(234, 8)

In [72]:
runnerups2021 = df2021_sorted.groupby('ac_number').nth(1).reset_index()

In [73]:
runnerups2021.head()

,index,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,1,Gummidipundi,1,PRAKASH M,PMK,75514,78.08,GEN,Chennai Metro
1,14,Ponneri,2,BALARAMAN. P,AIADMK,84839,78.20,SC,Chennai Metro
2,25,Tiruttani,3,G.Hari,AIADMK,91061,78.76,GEN,Chennai Metro
3,40,Thiruvallur,4,"RAMANAH, BE VEE",AIADMK,85008,77.20,GEN,Chennai Metro
4,52,Poonamallee,5,Rajamannar S X,PMK,55468,72.99,SC,Chennai Metro

In [74]:
runnerups2021.shape

(234, 9)

In [75]:
winners2021 = winners2021.rename(columns={
    'candidate': 'winner_candidate',
    'party': 'winner_party',
    'votes': 'winner_votes'
})

In [76]:
runnerups2021 = runnerups2021.rename(columns={
    'candidate': 'runnerup_candidate',
    'party': 'runnerup_party',
    'votes': 'runnerup_votes'
})

In [77]:
final2021 = pd.merge(
    winners2021[
        ['ac_number', 'constituency', 'winner_candidate', 'winner_party', 'winner_votes']
    ],
    
    runnerups2021[
        ['ac_number', 'runnerup_candidate', 'runnerup_party', 'runnerup_votes']
    ],
    
    on='ac_number'
)

In [78]:
final2021.head()

,ac_number,constituency,winner_candidate,winner_party,winner_votes,runnerup_candidate,runnerup_party,runnerup_votes
0,1,Gummidipundi,GOVINDARAJAN T.J,DMK,126452,PRAKASH M,PMK,75514
1,2,Ponneri,DURAI. CHANDRASEKAR,INC,94528,BALARAMAN. P,AIADMK,84839
2,3,Tiruttani,S.Chandran,DMK,120314,G.Hari,AIADMK,91061
3,4,Thiruvallur,"RAAJENDRAN, V.G.",DMK,107709,"RAMANAH, BE VEE",AIADMK,85008
4,5,Poonamallee,Krishnaswamy A,DMK,149578,Rajamannar S X,PMK,55468

In [79]:
final2021['margin'] = (
    final2021['winner_votes'] -
    final2021['runnerup_votes']
)

In [80]:
final2021.head()

,ac_number,constituency,winner_candidate,winner_party,winner_votes,runnerup_candidate,runnerup_party,runnerup_votes,margin
0,1,Gummidipundi,GOVINDARAJAN T.J,DMK,126452,PRAKASH M,PMK,75514,50938
1,2,Ponneri,DURAI. CHANDRASEKAR,INC,94528,BALARAMAN. P,AIADMK,84839,9689
2,3,Tiruttani,S.Chandran,DMK,120314,G.Hari,AIADMK,91061,29253
3,4,Thiruvallur,"RAAJENDRAN, V.G.",DMK,107709,"RAMANAH, BE VEE",AIADMK,85008,22701
4,5,Poonamallee,Krishnaswamy A,DMK,149578,Rajamannar S X,PMK,55468,94110

In [81]:
final2021.shape

(234, 9)

In [82]:
df2026_sorted = df2026.sort_values(
    ['ac_number', 'votes'],
    ascending=[True, False]
)

In [83]:
df2026_sorted.head(20)

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro
1,Gummidipoondi,1,SUDHAKAR.V,AIADMK,66375,NaN,GEN,Chennai Metro
2,Gummidipoondi,1,T.J.GOVINDARAJAN,DMK,62492,NaN,GEN,Chennai Metro
3,Gummidipoondi,1,"R.SRIDAR. B.L.,",NTK,4756,NaN,GEN,Chennai Metro
4,Gummidipoondi,1,NOTA,NOTA,937,NaN,GEN,Chennai Metro
5,Gummidipoondi,1,M.JAGADEESAN,Bahujan Samaj Party,697,NaN,GEN,Chennai Metro
6,Gummidipoondi,1,SDK SANKAR,Aanaithinthiya Jananayaka Pathukappu Kazhagam,599,NaN,GEN,Chennai Metro
7,Gummidipoondi,1,G.RANJITH B.SC.L.L.B,IND,503,NaN,GEN,Chennai Metro
8,Gummidipoondi,1,K. CHANDRA SEKAR,Veerath Thiyagi Viswanathadoss Thozhilalarkal ...,336,NaN,GEN,Chennai Metro
9,Gummidipoondi,1,D.SUDHAKAR,IND,321,NaN,GEN,Chennai Metro
10,Gummidipoondi,1,M.KUMARAN,IND,260,NaN,GEN,Chennai Metro
11,Gummidipoondi,1,D.DINESH,IND,222,NaN,GEN,Chennai Metro
12,Gummidipoondi,1,V.SUDHAKAR,IND,217,NaN,GEN,Chennai Metro
13,Gummidipoondi,1,T.GOVINDAN,IND,206,NaN,GEN,Chennai Metro
14,Gummidipoondi,1,GOPAL.K,IND,177,NaN,GEN,Chennai Metro
15,Gummidipoondi,1,A.H. SIVA GANESH,IND,104,NaN,GEN,Chennai Metro
16,Ponneri,2,DR.RAVI.M.S,TVK,110439,NaN,SC,Chennai Metro
17,Ponneri,2,DURAI CHANDRASEKAR,INC,54671,NaN,SC,Chennai Metro
18,Ponneri,2,BALARAMAN.P,AIADMK,51468,NaN,SC,Chennai Metro
19,Ponneri,2,RAJATHI.M,NTK,6676,NaN,SC,Chennai Metro

In [84]:
winners2026 = df2026_sorted.groupby('ac_number').first().reset_index()

In [85]:
winners2026.head()

,ac_number,constituency,candidate,party,votes,turnout,reserved,region
0,1,Gummidipoondi,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro
1,2,Ponneri,DR.RAVI.M.S,TVK,110439,NaN,SC,Chennai Metro
2,3,Tiruttani,G.HARI,AIADMK,89169,NaN,GEN,Chennai Metro
3,4,Thiruvallur,DR. T. ARUNKUMAR,TVK,92190,NaN,GEN,Chennai Metro
4,5,Poonamallee,PRAKASAM.R,TVK,161309,NaN,SC,Chennai Metro

In [86]:
winners2021.shape

(234, 8)

In [87]:
runnerups2026 = df2026_sorted.groupby('ac_number').nth(1).reset_index()

In [88]:
runnerups2026.head()

,index,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,1,Gummidipoondi,1,SUDHAKAR.V,AIADMK,66375,NaN,GEN,Chennai Metro
1,17,Ponneri,2,DURAI CHANDRASEKAR,INC,54671,NaN,SC,Chennai Metro
2,31,Tiruttani,3,M.SATHYA KUMAR,TVK,83376,NaN,GEN,Chennai Metro
3,45,Thiruvallur,4,V.G. RAAJENDRAN,DMK,67430,NaN,GEN,Chennai Metro
4,60,Poonamallee,5,KRISHNASWAMY.A,DMK,88569,NaN,SC,Chennai Metro

In [89]:
runnerups2026.shape

(234, 9)

In [90]:
winners2026 = winners2026.rename(columns={
    'candidate': 'winner_candidate',
    'party': 'winner_party',
    'votes': 'winner_votes'
})

In [91]:
runnerups2026 = runnerups2026.rename(columns={
    'candidate': 'runnerup_candidate',
    'party': 'runnerup_party',
    'votes': 'runnerup_votes'
})

In [92]:
final2026 = pd.merge(
    winners2026[
        ['ac_number', 'constituency', 'winner_candidate', 'winner_party', 'winner_votes']
    ],
    
    runnerups2026[
        ['ac_number', 'runnerup_candidate', 'runnerup_party', 'runnerup_votes']
    ],
    
    on='ac_number'
)

In [93]:
final2026.head()

,ac_number,constituency,winner_candidate,winner_party,winner_votes,runnerup_candidate,runnerup_party,runnerup_votes
0,1,Gummidipoondi,S.VIJAYAKUMAR,TVK,94320,SUDHAKAR.V,AIADMK,66375
1,2,Ponneri,DR.RAVI.M.S,TVK,110439,DURAI CHANDRASEKAR,INC,54671
2,3,Tiruttani,G.HARI,AIADMK,89169,M.SATHYA KUMAR,TVK,83376
3,4,Thiruvallur,DR. T. ARUNKUMAR,TVK,92190,V.G. RAAJENDRAN,DMK,67430
4,5,Poonamallee,PRAKASAM.R,TVK,161309,KRISHNASWAMY.A,DMK,88569

In [94]:
final2026['margin'] = (
    final2026['winner_votes'] -
    final2026['runnerup_votes']
)

In [95]:
final2026.head()

,ac_number,constituency,winner_candidate,winner_party,winner_votes,runnerup_candidate,runnerup_party,runnerup_votes,margin
0,1,Gummidipoondi,S.VIJAYAKUMAR,TVK,94320,SUDHAKAR.V,AIADMK,66375,27945
1,2,Ponneri,DR.RAVI.M.S,TVK,110439,DURAI CHANDRASEKAR,INC,54671,55768
2,3,Tiruttani,G.HARI,AIADMK,89169,M.SATHYA KUMAR,TVK,83376,5793
3,4,Thiruvallur,DR. T. ARUNKUMAR,TVK,92190,V.G. RAAJENDRAN,DMK,67430,24760
4,5,Poonamallee,PRAKASAM.R,TVK,161309,KRISHNASWAMY.A,DMK,88569,72740

In [96]:
final2026.shape

(234, 9)

In [97]:
compare2021 = final2021[
    ['ac_number', 'constituency', 'winner_party']
].rename(columns={
    'winner_party': 'winner_party_2021'
})

In [98]:
compare2026 = final2026[
    ['ac_number', 'winner_party']
].rename(columns={
    'winner_party': 'winner_party_2026'
})

In [99]:
flip_analysis = pd.merge(
    compare2021,
    compare2026,
    on='ac_number'
)

In [100]:
flip_analysis['flipped'] = (
    flip_analysis['winner_party_2021'] !=
    flip_analysis['winner_party_2026']
)

In [101]:
flip_analysis.head()

   ac_number  constituency winner_party_2021 winner_party_2026  flipped
0          1  Gummidipundi               DMK               TVK     True
1          2       Ponneri               INC               TVK     True
2          3     Tiruttani               DMK            AIADMK     True
3          4   Thiruvallur               DMK               TVK     True
4          5   Poonamallee               DMK               TVK     True

In [102]:
flip_analysis['flipped'].sum()

np.int64(163)

In [103]:
flipped_seats = flip_analysis[
    flip_analysis['flipped'] == True
]

In [104]:
final2021 = pd.merge(
    final2021,
    
    master[['ac_number', 'region', 'reserved']],
    
    on='ac_number',
    how='left'
)

In [105]:
final2026 = pd.merge(
    final2026,
    
    master[['ac_number', 'region', 'reserved']],
    
    on='ac_number',
    how='left'
)

In [106]:
final2021.head()

,ac_number,constituency,winner_candidate,winner_party,winner_votes,runnerup_candidate,runnerup_party,runnerup_votes,margin,region,reserved
0,1,Gummidipundi,GOVINDARAJAN T.J,DMK,126452,PRAKASH M,PMK,75514,50938,Chennai Metro,GEN
1,2,Ponneri,DURAI. CHANDRASEKAR,INC,94528,BALARAMAN. P,AIADMK,84839,9689,Chennai Metro,SC
2,3,Tiruttani,S.Chandran,DMK,120314,G.Hari,AIADMK,91061,29253,Chennai Metro,GEN
3,4,Thiruvallur,"RAAJENDRAN, V.G.",DMK,107709,"RAMANAH, BE VEE",AIADMK,85008,22701,Chennai Metro,GEN
4,5,Poonamallee,Krishnaswamy A,DMK,149578,Rajamannar S X,PMK,55468,94110,Chennai Metro,SC

In [107]:
final2026.head()

,ac_number,constituency,winner_candidate,winner_party,winner_votes,runnerup_candidate,runnerup_party,runnerup_votes,margin,region,reserved
0,1,Gummidipoondi,S.VIJAYAKUMAR,TVK,94320,SUDHAKAR.V,AIADMK,66375,27945,Chennai Metro,GEN
1,2,Ponneri,DR.RAVI.M.S,TVK,110439,DURAI CHANDRASEKAR,INC,54671,55768,Chennai Metro,SC
2,3,Tiruttani,G.HARI,AIADMK,89169,M.SATHYA KUMAR,TVK,83376,5793,Chennai Metro,GEN
3,4,Thiruvallur,DR. T. ARUNKUMAR,TVK,92190,V.G. RAAJENDRAN,DMK,67430,24760,Chennai Metro,GEN
4,5,Poonamallee,PRAKASAM.R,TVK,161309,KRISHNASWAMY.A,DMK,88569,72740,Chennai Metro,SC

In [108]:
region_2021 = (
    final2021
    .groupby(['region', 'winner_party'])
    .size()
    .reset_index(name='seats_won')
)

In [109]:
region_2026 = (
    final2026
    .groupby(['region', 'winner_party'])
    .size()
    .reset_index(name='seats_won')
)

In [111]:
region_2026.head()

    region winner_party  seats_won
0  Central       AIADMK         15
1  Central         DMDK          1
2  Central          DMK          8
3  Central          PMK          3
4  Central          TVK         12

In [112]:
region_2021_sorted = region_2021.sort_values(
    ['region', 'seats_won'],
    ascending=[True, False]
)

In [113]:
region_2026_sorted = region_2026.sort_values(
    ['region', 'seats_won'],
    ascending=[True, False]
)

In [114]:
region_2021_sorted

           region winner_party  seats_won
1         Central          DMK         21
0         Central       AIADMK         15
3         Central          PMK          3
2         Central          INC          1
4         Central          VCK          1
5   Chennai Metro          DMK         29
6   Chennai Metro          INC          3
10          Delta          DMK         23
7           Delta       AIADMK          4
9           Delta       CPI(M)          2
11          Delta          INC          2
8           Delta          CPI          1
12          Delta          VCK          1
13          Kongu       AIADMK         19
15          Kongu          DMK         10
14          Kongu          BJP          2
16          Kongu          INC          2
19          North          DMK         19
17          North       AIADMK         12
21          North          PMK          2
22          North          VCK          2
18          North          CPI          1
20          North          INC          1
25          South          DMK         31
23          South       AIADMK         16
26          South          INC          9
24          South          BJP          2

In [115]:
region_2026_sorted

           region winner_party  seats_won
0         Central       AIADMK         15
4         Central          TVK         12
2         Central          DMK          8
3         Central          PMK          3
5         Central          VCK          2
1         Central         DMDK          1
8   Chennai Metro          TVK         29
7   Chennai Metro          DMK          2
6   Chennai Metro       AIADMK          1
13          Delta          DMK         14
16          Delta          TVK         10
9           Delta       AIADMK          4
10          Delta         AMMK          1
11          Delta          CPI          1
12          Delta       CPI(M)          1
14          Delta          INC          1
15          Delta         IUML          1
20          Kongu          TVK         16
19          Kongu          DMK          9
17          Kongu       AIADMK          7
18          Kongu          BJP          1
21          North       AIADMK         15
26          North          TVK         15
23          North          DMK          4
22          North          CPI          1
24          North         IUML          1
25          North          PMK          1
31          South          TVK         26
29          South          DMK         22
27          South       AIADMK          5
30          South          INC          4
28          South       CPI(M)          1

In [116]:
top_region_2021 = (
    region_2021_sorted
    .groupby('region')
    .first()
    .reset_index()
)

In [117]:
top_region_2026 = (
    region_2026_sorted
    .groupby('region')
    .first()
    .reset_index()
)

In [118]:
top_region_2021

          region winner_party  seats_won
0        Central          DMK         21
1  Chennai Metro          DMK         29
2          Delta          DMK         23
3          Kongu       AIADMK         19
4          North          DMK         19
5          South          DMK         31

In [119]:
top_region_2026

          region winner_party  seats_won
0        Central       AIADMK         15
1  Chennai Metro          TVK         29
2          Delta          DMK         14
3          Kongu          TVK         16
4          North       AIADMK         15
5          South          TVK         26

In [120]:
avg_margin_2021 = final2021['margin'].mean()
avg_margin_2026 = final2026['margin'].mean()

print("2021 Average Margin:", avg_margin_2021)
print("2026 Average Margin:", avg_margin_2026)

2021 Average Margin: 22870.547008547008
2026 Average Margin: 16784.24358974359

In [122]:
closest_2026 = final2026.sort_values(
    by='margin'
).head(10)

In [123]:
closest_2026[
    [
        'constituency',
        'winner_candidate',
        'winner_party',
        'runnerup_candidate',
        'runnerup_party',
        'margin'
    ]
]

,constituency,winner_candidate,winner_party,runnerup_candidate,runnerup_party,margin
184,Tiruppattur,SEENIVASA SETHUPATHY. R,TVK,PERIAKARUPPAN. KR,DMK,1
53,Veppanahalli,SRINIVASAN.P.S,DMK,MUNUSAMY.K.P,AIADMK,138
228,Kanniyakumari,THALAVAI SUNDARAM. N,AIADMK,MAHESH.R,DMK,214
65,Polur,ABISHEK. R,TVK,SARAVANAN. P,DMDK,227
75,Tirukkoyilur,PALANISAMY S,AIADMK,VIJAY R BARANIBALAAJI,TVK,285
94,Paramathi-Velur,SEKAR S,AIADMK,MOORTHIY K S,DMK,308
136,Kulithalai,SURIYANUR. A. CHANDRAN,DMK,G.BALASUBRAMANI,TVK,579
170,Kumbakonam,VINOTH,TVK,ANBALAGAN G,DMK,679
126,Palani,RAVIMANOHARAN. K,AIADMK,DR. PRAVEEN KUMAR. M,TVK,693
71,Tindivanam,VANNI ARASU,VCK,ARJUNAN. P,AIADMK,734

In [124]:
largest_2026 = final2026.sort_values(
    by='margin',
    ascending=False
).head(10)

In [125]:
largest_2026[
    [
        'constituency',
        'winner_candidate',
        'winner_party',
        'margin'
    ]
]

         constituency         winner_candidate winner_party  margin
85           Edappadi  EDAPPADI PALANISWAMI. K       AIADMK   98110
26    Shozhinganallur          ECR P SARAVANAN          TVK   96780
8           Madavaram          M.L.VIJAYPRABHU          TVK   94985
5               Avadi           R.RAMESH KUMAR          TVK   76311
87       Salem (West)             LAKSHMANAN.S          TVK   74867
4         Poonamallee               PRAKASAM.R          TVK   72740
112  Tiruppur (North)             V.SATHYABAMA          TVK   69992
178       Viralimalai          VIJAYABASKAR. C       AIADMK   62073
6         Maduravoyal          RHEVANTH CHARAN          TVK   61509
7            Ambattur            BALAMURUGAN.G          TVK   58781

In [127]:
final2021.to_csv(
    "final2021.csv",
    index=False
)

In [128]:
final2026.to_csv(
    "final2026.csv",
    index=False
)

In [129]:
flip_analysis.to_csv(
    "flip_analysis.csv",
    index=False
)

In [131]:
region_2021.to_csv(
    "region_2021.csv",
    index=False
)

In [132]:
region_2026.to_csv(
    "region_2026.csv",
    index=False
)

In [133]:
region_compare = pd.merge(
    top_region_2021,
    top_region_2026,
    on='region'
)

In [134]:
region_compare.to_csv(
    "region_compare.csv",
    index=False
)